[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[program:postgresql]
command=su postgres -c "postgres -D /var/lib/postgresql/data"
autostart=true
autorestart=true

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true
